In [2]:
import numpy as np

In [4]:
# arange 
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# array 
a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])


In [24]:
#dimension,size,reshape,shape
print("The Dimension of Array is : ",a.ndim)
print("The Size Of Array is:",a.size)
print("The Shape Of array is:",a.shape)
print("The Shape of Array (after Reshaping):",a.reshape(3,3),sep=" \n")

The Dimension of Array is :  3
The Size Of Array is: 9
The Shape Of array is: (1, 3, 3)
The Shape of Array (after Reshaping): 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
#Zeros,ones,empty
print(np.zeros((3,3),dtype=int))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


AttributeError: module 'numpy' has no attribute 'zeroslike'