# Reading Recipes 

Note: Data file is recipes.csv Attached with jupyter notebook

In [4]:
#type your code here
import numpy as np
import csv

2. All of Alize’s recipes call for milk, eggs, sugar, flour, and butter. For example, her cupcake recipe calls for:

Flour Sugar Eggs Milk Butter 2 cups 0.75 cups 2 eggs 1 cups 0.5 cups Create a NumPy array that represents this data. Each element should be a number (i.e., 2 for “2 cups”). Save this array as cupcakes.

In [5]:
#type your code here
cupcakes= np.array([2,0.75,2,1,0.5])

3. Alize’s assistant has compiled all of her recipes into a csv (comma-separated variable) file called recipes.csv. Load this file into a variable called recipes.

###########Explore yourselves how to load a csv file in numpy#######

In [7]:
#type your code here
recipes = np.loadtxt("recipes.csv",delimiter=',')
recipes

array([[2.   , 0.75 , 2.   , 1.   , 0.5  ],
       [1.   , 0.125, 1.   , 1.   , 0.125],
       [2.75 , 1.5  , 1.   , 0.   , 1.   ],
       [4.   , 0.5  , 2.   , 2.   , 0.5  ]])

4.Display recipes using print.
Display recipes using print.


Each row represents a different recipe. Each column represents a different ingredient.

Recipe	       Cups of Flour	Cups of Sugar	Eggs	Cups of Milk	Cups of Butter

Cupcakes	         …	              …	          …	         …	              …

Pancake	             …                …	          …	         …	              …

Cookie	             …	              …	          …	         …	              …

Bread	             …	              …	          …	         …	              …

In [12]:
#type your code here
print("Recipe            Cups of Flour            Cups of Sugar            Eggs            Cups of Milk            Cups of Butter")
repNames = ["Cupcakes","Panacakes","Cookie","Bread"]
name = 0
for i in recipes:
    print(f"{repNames[name]} {' '*10} {i[0]} {' '*20} {i[1]} {' '*15}  {i[2]} {' '*15} {i[3]} {' '*15} {i[4]}")
    name+=1


Recipe            Cups of Flour            Cups of Sugar            Eggs            Cups of Milk            Cups of Butter
Cupcakes            2.0                      0.75                  2.0                 1.0                 0.5
Panacakes            1.0                      0.125                  1.0                 1.0                 0.125
Cookie            2.75                      1.5                  1.0                 0.0                 1.0
Bread            4.0                      0.5                  2.0                 2.0                 0.5


5.The 3rd column represents the number of eggs that each recipe needs.

Select all elements from the 3rd column and save them to the variable eggs.

In [16]:
#type your code here
eggs =recipes[:,2].astype("i")
eggs

array([2, 1, 1, 2], dtype=int32)

6.Which recipes require exactly 1 egg? Use a logical statement to get True or False for each value of eggs.

In [17]:
#type your code here
eggs ==1


array([False,  True,  True, False])

7.Alize is going to make 2 batches of cupcakes (1st row) and 1 batch of cookies (3rd row).

You already have a variable for cupcakes. Create a variable for cookies with the data from the 3rd row.


In [12]:
#type your code here


8.
Get the number of ingredients for a double batch of cupcakes by using multiplication on cupcakes. Save your new variable to double_batch.

In [ ]:
#type your code here


9.
Create a new variable called grocery_list by adding cookies and double_batch.

In [ ]:
#type your code here
